### ISSUE TITLE
按照官方流程安装，报错了

### ISSUE THREAD

**Issue by yinghanzi** [tyxsspa/AnyText#11]
2023-12-29 15:19:56,915 - modelscope - WARNING - ('PIPELINES', 'my-anytext-task', 'my-custom-pipeline') not found in ast index file
2023-12-29 15:19:56,915 - modelscope - INFO - initiate model from C:\Users\sunny\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing
2023-12-29 15:19:56,915 - modelscope - INFO - initiate model from location C:\Users\sunny\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing.
2023-12-29 15:19:56,916 - modelscope - INFO - initialize model from C:\Users\sunny\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing
2023-12-29 15:19:56,919 - modelscope - WARNING - ('MODELS', 'my-anytext-task', 'my-custom-model') not found in ast index file
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

按照官方流程安装，报错了
<img width="763" alt="微信图片_20231229152448" src="https://github.com/tyxsspa/AnyText/assets/121802291/ae93b23a-b9f6-43a0-abcb-3088cbf19260">
![Uploading 微信图片_20231229152448.png…]()

**Comment by feliming** [comment]
我的报错还略有一点不一样：

(anytext) PS F:\projects\AnyText> python demo.py
2024-01-03 11:11:32,479 - modelscope - INFO - PyTorch version 2.0.1 Found.
2024-01-03 11:11:32,508 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2024-01-03 11:11:32,508 - modelscope - INFO - Loading ast index from C:\Users\admin\.cache\modelscope\ast_indexer
2024-01-03 11:11:33,593 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 bcfece09e97aff36e92e44fcbdcf494f and a total number of 946 components indexed
2024-01-03 11:11:41,423 - modelscope - INFO - Use user-specified model revision: v1.1.0
2024-01-03 11:11:53,120 - modelscope - WARNING - ('PIPELINES', 'my-anytext-task', 'my-custom-pipeline') not found in ast index file
2024-01-03 11:11:53,120 - modelscope - INFO - initiate model from C:\Users\admin\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing
2024-01-03 11:11:53,120 - modelscope - INFO - initiate model from location C:\Users\admin\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing.
2024-01-03 11:11:53,122 - modelscope - INFO - initialize model from C:\Users\admin\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing        
2024-01-03 11:11:53,125 - modelscope - WARNING - ('MODELS', 'my-anytext-task', 'my-custom-model') not found in ast index file
Traceback (most recent call last):
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\utils\registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\models\base\base_model.py", line 67, in _instantiate
    return cls(**kwargs)
  File "C:\Users\admin\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 43, in __init__   
    self.init_model(**kwargs)
  File "C:\Users\admin\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 218, in init_model
    self.font = ImageFont.truetype(font_path, size=60)
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\admin\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 320, in __init__
    super().__init__(model=model, auto_collate=False)
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\pipelines\base.py", line 99, in __init__
    self.model = self.initiate_single_model(model)
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\pipelines\base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\models\base\base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\models\builder.py", line 35, in build_model
    model = build_from_cfg(
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: MyCustomModel: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\projects\AnyText\demo.py", line 21, in <module>
    inference = pipeline('my-anytext-task', model='damo/cv_anytext_text_generation_editing', model_revision='v1.1.0')
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "D:\Programs\miniconda3\envs\anytext\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: MyCustomPipeline: MyCustomModel: cannot open resource

环境 Win10、Python 3.12

**Comment by tyxsspa** [comment]
> PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)

Hi, 检查下你安装的pytorch，是不是CPU版的？

**Comment by i-am-vt** [comment]
I have the same error as you, and it seems that the official provided code is not working as expected. I had to manually execute `conda install pytorch==2.0.1 torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia` to make it work.
Then I encountered a second issue, which is an charset problem. If you also encounter it, add "encoding='UTF-8'" to all the open calls.

**Comment by StarLuckLee** [comment]
> 我和你有同样的错误，看来官方提供的代码没有按预期工作。我必须手动执行`conda install pytorch==2.0.1 torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia` 并指定`KMP_DUPLICATE_LIB_OK=TRUE`才能使其工作。 然后我又遇到了第二个问题，就是字符集问题。如果您也遇到这种情况，请在所有打开的调用中添加“encoding='UTF-8'”。

我也碰到了这个问题，请问 " 指定`KMP_DUPLICATE_LIB_OK=TRUE` " 这一步怎么操作？

**Comment by i-am-vt** [comment]
> > 我和你有同样的错误，看来官方提供的代码没有按预期工作。我必须手动执行`conda install pytorch==2.0.1 torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia` 并指定`KMP_DUPLICATE_LIB_OK=TRUE`才能使其工作。 然后我又遇到了第二个问题，就是字符集问题。如果您也遇到这种情况，请在所有打开的调用中添加“encoding='UTF-8'”。
> 
> 我也碰到了这个问题，请问 " 指定`KMP_DUPLICATE_LIB_OK=TRUE` " 这一步怎么操作？

Add that to an environment variable, for example, use "`set KMP_DUPLICATE_LIB_OK=TRUE`" for Windows or "`export KMP_DUPLICATE_LIB_OK=TRUE`" for Unix-like systems.

**Comment by StarLuckLee** [comment]
> > > 我和你也有同样的错误，看来官方提供的代码没有按预期工作。我必须手动执行`conda install pytorch==2.0.1 torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`并指定`KMP_DUPLICATE_LIB_OK=TRUE`权限工作。然后我又遇到了第二个问题，就是字符集问题。如果您也遇到这种情况，请在所有打开的调用中添加“encoding='UTF-8'”。
> > 
> > 
> > 我也搞清楚了这个问题，请问“指定`KMP_DUPLICATE_LIB_OK=TRUE`”这一步怎么操作？
> 
> 将其添加到环境变量中，例如，`set KMP_DUPLICATE_LIB_OK=TRUE`对于 Windows 使用“”，`export KMP_DUPLICATE_LIB_OK=TRUE`对于类 Unix 系统使用“”。

万分感激你的回复与指导，仿佛把我拉出无尽黑暗的深渊，感谢！

**Comment by TheMQ** [comment]
> I have the same error as you, and it seems that the official provided code is not working as expected. I had to manually execute `conda install pytorch==2.0.1 torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia` and specify `KMP_DUPLICATE_LIB_OK=TRUE` to make it work. Then I encountered a second issue, which is an charset problem. If you also encounter it, add "encoding='UTF-8'" to all the "open" function calls.

我执行了你提到的方式，但是遇到了三个报错：RemoveError: 'tqdm' is a dependency of conda and cannot be removed from
conda's operating environment.
RemoveError: 'platformdirs' is a dependency of conda and cannot be removed from
conda's operating environment.
RemoveError: 'zstandard' is a dependency of conda and cannot be removed from
conda's operating environment. 请问该如何解决这样的问题？
