### ISSUE TITLE
Ubuntu no Airal Font! (Solved)

### ISSUE THREAD

**Issue by yhyu13** [tyxsspa/AnyText#19]
Hi,

I install environment using environment.yaml

There is an error loading specific fonts on Ubuntu machines

And I assume code was written for windows machine only?

The cv_anytext_text_generation_editing model would require loading a font by default, the font default path is ```font/Arial_Unicode.ttf``` in modelscope                   1.10.0 

```
2024-01-02 07:10:36,030 - modelscope - INFO - PyTorch version 2.0.1 Found.
2024-01-02 07:10:36,031 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2024-01-02 07:10:36,031 - modelscope - INFO - Loading ast index from /home/hangyu5/.cache/modelscope/ast_indexer
2024-01-02 07:10:36,062 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 c8dda4735ccce9e1c5d4bb482f4b5560 and a total number of 946 components indexed
2024-01-02 07:10:37,460 - modelscope - INFO - Use user-specified model revision: v1.1.0
2024-01-02 07:10:40,421 - modelscope - WARNING - ('PIPELINES', 'my-anytext-task', 'my-custom-pipeline') not found in ast index file
2024-01-02 07:10:40,421 - modelscope - INFO - initiate model from /home/hangyu5/.cache/modelscope/hub/damo/cv_anytext_text_generation_editing
2024-01-02 07:10:40,421 - modelscope - INFO - initiate model from location /home/hangyu5/.cache/modelscope/hub/damo/cv_anytext_text_generation_editing.
2024-01-02 07:10:40,425 - modelscope - INFO - initialize model from /home/hangyu5/.cache/modelscope/hub/damo/cv_anytext_text_generation_editing
2024-01-02 07:10:40,427 - modelscope - WARNING - ('MODELS', 'my-anytext-task', 'my-custom-model') not found in ast index file
Traceback (most recent call last):
  File "/home/hangyu5/anaconda3/envs/anytext/lib/python3.10/site-packages/modelscope/utils/registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "/home/hangyu5/anaconda3/envs/anytext/lib/python3.10/site-packages/modelscope/models/base/base_model.py", line 67, in _instantiate
    return cls(**kwargs)
  File "/home/hangyu5/.cache/modelscope/modelscope_modules/cv_anytext_text_generation_editing/ms_wrapper.py", line 43, in __init__
    self.init_model(**kwargs)
  File "/home/hangyu5/.cache/modelscope/modelscope_modules/cv_anytext_text_generation_editing/ms_wrapper.py", line 218, in init_model
    self.font = ImageFont.truetype(font_path, size=60)
  File "/home/hangyu5/anaconda3/envs/anytext/lib/python3.10/site-packages/PIL/ImageFont.py", line 996, in truetype
    return freetype(font)
  File "/home/hangyu5/anaconda3/envs/anytext/lib/python3.10/site-packages/PIL/ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/hangyu5/anaconda3/envs/anytext/lib/python3.10/site-packages/PIL/ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by tyxsspa** [comment]
Hi, this font file is copyrighted, and we cannot provide a download. You will need to prepare it yourself, as comments in the **Installation** section:
```
# Prepare a font file; Arial Unicode MS is recommended, **you need to download it on your own**
mv your/path/to/arialuni.ttf ./font/Arial_Unicode.ttf
```

**Comment by yhyu13** [comment]
> Hi, this font file is copyrighted, and we cannot provide a download. You will need to prepare it yourself, as comments in the **Installation** section:
> 
> ```
> # Prepare a font file; Arial Unicode MS is recommended, **you need to download it on your own**
> mv your/path/to/arialuni.ttf ./font/Arial_Unicode.ttf
> ```

I found link to the font which would work https://freefonts.co/fonts/arial-unicode-ms-regular

**Comment by tyxsspa** [comment]
> ok, Thnaks!
> 
> Is there a way to config the path to the font other than the default path? The font_path argument is part of some config file I believe

Yes, you can modify the MyCustomModel::init_model() in ms_wrapper.py(this file is located at where your model downloaded, by default it's: `~/.cache/modelscope/hub`):
```
def init_model(self, **kwargs):
    font_path = kwargs.get('font_path', 'font/Arial_Unicode.ttf')  # <---Here!
    self.font = ImageFont.truetype(font_path, size=60)
    cfg_path = kwargs.get('cfg_path', 'models_yaml/anytext_sd15.yaml')
    ckpt_path = kwargs.get('model_path', os.path.join(self.model_dir, 'anytext_v1.1.ckpt'))
    clip_path = os.path.join(self.model_dir, 'clip-vit-large-patch14')
    self.model = create_model(cfg_path, cond_stage_path=clip_path).cuda().eval()
    self.model.load_state_dict(load_state_dict(ckpt_path, location='cuda'), strict=False)
    self.ddim_sampler = DDIMSampler(self.model)
    self.trans_pipe = pipeline(task=Tasks.translation, model=os.path.join(self.model_dir, 'nlp_csanmt_translation_zh2en'))
```

**Comment by yhyu13** [comment]
@tyxsspa That file is protected by some modelscope revision mechanism that will reset my modification before loading the model.

**Comment by tyxsspa** [comment]
> @tyxsspa That file is protected by some modelscope revision mechanism that will reset my modification before loading the model.
This is a bit strange. In my case, as long as the file name is not changed, modifying the code does not trigger the model scope revision mechanism.
