### ISSUE TITLE
TypeError: MyCustomPipeline: MyCustomModel: DataLossError.__init__() missing 2 required positional arguments: 'op' and 'message'

### ISSUE THREAD

**Issue by wangwenqiao666** [tyxsspa/AnyText#20]
Traceback (most recent call last):
  File "/data/AnyText/inference.py", line 3, in <module>
    pipe = pipeline('my-anytext-task', model='damo/cv_anytext_text_generation_editing', model_revision='v1.1.0')
  File "/data/AnyText/python/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/data/AnyText/python/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/data/AnyText/python/lib/python3.10/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: MyCustomPipeline: MyCustomModel: DataLossError.__init__() missing 2 required positional arguments: 'op' and 'message'

**Comment by DoubleCake** [comment]
When i us wsl in windows10 .I got the same issue.
Then I solved this problem by using ubuntu 22.04 。

**Comment by wangwenqiao666** [comment]
> 当我在 windows10 中使用 wsl 时，我遇到了同样的问题。 然后我使用 ubuntu 22.04 解决了这个问题。

This is the missing configuration file, I used git clone to download, not complete, and then re-manually download it

**Comment by jason571** [comment]
Can you share you tensorFlow version?

**Comment by Wangxunhang** [comment]
> > 当我在 windows10 中使用 wsl 时，我遇到了同样的问题。 然后我使用 ubuntu 22.04 解决了这个问题。
> 
> This is the missing configuration file, I used git clone to download, not complete, and then re-manually download it

请问你重新下载的是项目文件还是模型文件?

**Comment by wangwenqiao666** [comment]
> > > 当我在 windows10 中使用 wsl 时，我遇到了同样的问题。 然后我使用 ubuntu 22.04 解决了这个问题。
> > 
> > 
> > This is the missing configuration file, I used git clone to download, not complete, and then re-manually download it
> 
> 请问你重新下载的是项目文件还是模型文件?

  模型文件
