### ISSUE TITLE
run error : MyCustomModel: cannot open resource

### ISSUE THREAD

**Issue by libhot** [tyxsspa/AnyText#3]
python  demo.py 
2023-12-27 13:25:47,978 - modelscope - INFO - PyTorch version 2.1.2 Found.
2023-12-27 13:25:47,981 - modelscope - INFO - TensorFlow version 2.15.0.post1 Found.
2023-12-27 13:25:47,981 - modelscope - INFO - Loading ast index from /share/model/cv_anytext_text_generation_editing/ast_indexer
2023-12-27 13:25:48,094 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 099672c06c5dce8e4240f79ebe0fd960 and a total number of 946 components indexed
2023-12-27 13:25:52,146 - modelscope - INFO - Use user-specified model revision: v1.1.0
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 56.0/56.0 [00:00<00:00, 426kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 1.06k/1.06k [00:00<00:00, 7.98MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████▉| 5.34G/5.34G [02:42<00:00, 35.3MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 345k/345k [00:00<00:00, 2.22MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 373k/373k [00:00<00:00, 2.40MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 69.0/69.0 [00:00<00:00, 511kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████▉| 7.34G/7.34G [03:31<00:00, 37.2MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 85.8k/85.8k [00:00<00:00, 823kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 10.0M/10.0M [00:00<00:00, 17.6MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 4.41k/4.41k [00:00<00:00, 289kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 2.07k/2.07k [00:00<00:00, 19.0MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 144/144 [00:00<00:00, 1.49MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 62.5k/62.5k [00:00<00:00, 838kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 62.9k/62.9k [00:00<00:00, 935kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 334k/334k [00:00<00:00, 2.09MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 512k/512k [00:00<00:00, 3.56MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 17.4k/17.4k [00:00<00:00, 617kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 316/316 [00:00<00:00, 2.35MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████▉| 1.59G/1.59G [00:50<00:00, 34.2MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 5.39k/5.39k [00:00<00:00, 419kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 7.76k/7.76k [00:00<00:00, 32.1MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 9.26k/9.26k [00:00<00:00, 256kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 546k/546k [00:00<00:00, 1.63MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 60.7k/60.7k [00:00<00:00, 677kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 3.48MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 327k/327k [00:00<00:00, 1.53MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 2.12M/2.12M [00:00<00:00, 2.69MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 905/905 [00:00<00:00, 5.90MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 152k/152k [00:00<00:00, 1.56MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 138k/138k [00:00<00:00, 1.48MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 320k/320k [00:00<00:00, 1.85MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 939k/939k [00:00<00:00, 2.64MB/s]
2023-12-27 13:34:17,636 - modelscope - WARNING - ('PIPELINES', 'my-anytext-task', 'my-custom-pipeline') not found in ast index file
2023-12-27 13:34:17,636 - modelscope - INFO - initiate model from /share/model/cv_anytext_text_generation_editing/damo/cv_anytext_text_generation_editing
2023-12-27 13:34:17,641 - modelscope - INFO - initiate model from location /share/model/cv_anytext_text_generation_editing/damo/cv_anytext_text_generation_editing.
2023-12-27 13:34:17,643 - modelscope - INFO - initialize model from /share/model/cv_anytext_text_generation_editing/damo/cv_anytext_text_generation_editing
2023-12-27 13:34:17,658 - modelscope - WARNING - ('MODELS', 'my-anytext-task', 'my-custom-model') not found in ast index file
Traceback (most recent call last):
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/utils/registry.py", line 210, in build_from_cfg
    return obj_cls._instantiate(**args)
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/models/base/base_model.py", line 67, in _instantiate
    return cls(**kwargs)
  File "/root/.cache/modelscope/modelscope_modules/cv_anytext_text_generation_editing/ms_wrapper.py", line 43, in __init__
    self.init_model(**kwargs)
  File "/root/.cache/modelscope/modelscope_modules/cv_anytext_text_generation_editing/ms_wrapper.py", line 218, in init_model
    self.font = ImageFont.truetype(font_path, size=60)
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/PIL/ImageFont.py", line 791, in truetype
    return freetype(font)
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/PIL/ImageFont.py", line 788, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/PIL/ImageFont.py", line 226, in __init__
    self.font = core.getfont(
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/utils/registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "/root/.cache/modelscope/modelscope_modules/cv_anytext_text_generation_editing/ms_wrapper.py", line 320, in __init__
    super().__init__(model=model, auto_collate=False)
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/pipelines/base.py", line 99, in __init__
    self.model = self.initiate_single_model(model)
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/pipelines/base.py", line 53, in initiate_single_model
    return Model.from_pretrained(
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/models/base/base_model.py", line 183, in from_pretrained
    model = build_model(model_cfg, task_name=task_name)
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/models/builder.py", line 35, in build_model
    model = build_from_cfg(
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: MyCustomModel: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/ai/AnyText-main/demo.py", line 20, in <module>
    inference = pipeline('my-anytext-task', model='damo/cv_anytext_text_generation_editing', model_revision='v1.1.0')
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/pipelines/builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "/opt/miniconda3/envs/anytext/lib/python3.10/site-packages/modelscope/utils/registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: MyCustomPipeline: MyCustomModel: cannot open resource

**Comment by tyxsspa** [comment]
Hi，
the codes and documentation are being updated and tested now, please wait.
This error occurs because you need to prepare the font file yourself, we recommend Arial Unicode MS, and then place it here:
```bash
mv your/path/to/arialuni.ttf AnyText/font/Arial_Unicode.ttf
```

**Comment by libhot** [comment]
> Hi， the codes and documentation are being updated and tested now, please wait. This error occurs because you need to prepare the font file yourself, we recommend Arial Unicode MS, and then place it here:
> 
> ```shell
> mv your/path/to/arialuni.ttf AnyText/font/Arial_Unicode.ttf
> ```

run successfully!
I thought all font files supported it.
Found no font selection option.

**Comment by Leobai** [comment]
even added the font, the same mistakes appeared

**Comment by Leobai** [comment]
even add the font, the same mistakes appeared

**Comment by tyxsspa** [comment]
> even added the font, the same mistakes appeared

Hi, please make sure the path and file name of your ttf is exactly: `AnyText/font/Arial_Unicode.ttf`

**Comment by wangwenqiao666** [comment]
download link：https://ultralytics.com/assets/Arial.ttf
then rename Arial_Unicode.ttf
