### ISSUE TITLE
中文编码错误

### ISSUE THREAD

**Issue by qdhonker** [tyxsspa/AnyText#36]
Loaded model config from [models_yaml/anytext_sd15.yaml]
Loaded state_dict from [C:\Users\Admin\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing\anytext_v1.1.ckpt]
2024-01-05 16:11:55,194 - modelscope - INFO - initiate model from C:\Users\Admin\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing\nlp_csanmt_translation_zh2en
2024-01-05 16:11:55,194 - modelscope - INFO - initiate model from location C:\Users\Admin\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing\nlp_csanmt_translation_zh2en.
2024-01-05 16:11:55,196 - modelscope - INFO - initialize model from C:\Users\Admin\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing\nlp_csanmt_translation_zh2en
{'hidden_size': 1024, 'filter_size': 4096, 'num_heads': 16, 'num_encoder_layers': 24, 'num_decoder_layers': 6, 'attention_dropout': 0.0, 'residual_dropout': 0.0, 'relu_dropout': 0.0, 'layer_preproc': 'layer_norm', 'layer_postpro
c': 'none', 'shared_embedding_and_softmax_weights': True, 'shared_source_target_embedding': True, 'initializer_scale': 0.1, 'position_info_type': 'absolute', 'max_relative_dis': 16, 'num_semantic_encoder_layers': 4, 'src_vocab_size': 50000, 'trg_vocab_size': 50000, 'seed': 1234, 'beam_size': 4, 'lp_rate': 0.6, 'max_decoded_trg_len': 100, 'device_map': None, 'device': 'cuda'}
2024-01-05 16:11:55,202 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2024-01-05 16:11:55,202 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'src_lang': 'zh', 'tgt_lang': 'en', 'src_bpe': {'file': 'bpe.zh'}, 'model_dir': 'C:\\Users\\Admin\\.cache\\modelscope\\hub\\damo\\cv_anytext_text_generation_editing\\nlp_csanmt_translation_zh2en'}. trying to build by task and model information.
2024-01-05 16:11:55,202 - modelscope - WARNING - No preprocessor key ('csanmt-translation', 'translation') found in PREPROCESSOR_MAP, skip building preprocessor.
Traceback (most recent call last):
  File "D:\AnyText\venv\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "D:\AnyText\venv\lib\site-packages\modelscope\pipelines\nlp\translation_pipeline.py", line 54, in __init__
    self._src_vocab = dict([
  File "D:\AnyText\venv\lib\site-packages\modelscope\pipelines\nlp\translation_pipeline.py", line 54, in <listcomp>
    self._src_vocab = dict([
UnicodeDecodeError: 'gbk' codec can't decode byte 0x84 in position 7: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AnyText\venv\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\Admin\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 336, in __init__
    pipe_model = AnyTextModel(model_dir=model, **kwargs)
  File "C:\Users\Admin\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 46, in __init__
    self.init_model(**kwargs)
  File "C:\Users\Admin\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 240, in init_model
    self.trans_pipe = pipeline(task=Tasks.translation, model=os.path.join(self.model_dir, 'nlp_csanmt_translation_zh2en'))
  File "D:\AnyText\venv\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\AnyText\venv\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "D:\AnyText\venv\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: function takes exactly 5 arguments (1 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AnyText\inference.py", line 3, in <module>
    pipe = pipeline('my-anytext-task', model='damo/cv_anytext_text_generation_editing', model_revision='v1.1.1')
  File "D:\AnyText\venv\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\AnyText\venv\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "D:\AnyText\venv\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: AnyTextPipeline: function takes exactly 5 arguments (1 given)

**Comment by tyxsspa** [comment]
和这个类似？https://github.com/tyxsspa/AnyText/issues/22

**Comment by yinghanzi** [comment]
基本上都是这个错误，如果按照大家说得添加“encoding='UTF-8'”依然解决不来问题。是不是在Windows上跑不起来呢？
