### ISSUE TITLE
Got error with yaml, I need some help. Please help,thank you

### ISSUE THREAD

**Issue by heroki0817** [tyxsspa/AnyText#37]
(anytext) PS E:\AI_Tools\anytext> python inference.py
Traceback (most recent call last):
  File "E:\AI_Tools\anytext\inference.py", line 1, in <module>
    from modelscope.pipelines import pipeline
  File "C:\Users\hekan\anaconda3\envs\anytext\lib\site-packages\modelscope\__init__.py", line 4, in <module>
    from modelscope.utils.import_utils import LazyImportModule
  File "C:\Users\hekan\anaconda3\envs\anytext\lib\site-packages\modelscope\utils\__init__.py", line 1, in <module>
    from .hub import create_model_if_not_exist, read_config
  File "C:\Users\hekan\anaconda3\envs\anytext\lib\site-packages\modelscope\utils\hub.py", line 12, in <module>
    from modelscope.utils.config import Config
  File "C:\Users\hekan\anaconda3\envs\anytext\lib\site-packages\modelscope\utils\config.py", line 22, in <module>
    from modelscope.utils.import_utils import import_modules_from_file
  File "C:\Users\hekan\anaconda3\envs\anytext\lib\site-packages\modelscope\utils\import_utils.py", line 18, in <module>
    from modelscope.utils.ast_utils import (INDEX_KEY, MODULE_KEY, REQUIREMENT_KEY,
  File "C:\Users\hekan\anaconda3\envs\anytext\lib\site-packages\modelscope\utils\ast_utils.py", line 16, in <module>
    from modelscope.fileio.file import LocalStorage
  File "C:\Users\hekan\anaconda3\envs\anytext\lib\site-packages\modelscope\fileio\__init__.py", line 4, in <module>
    from .io import dump, dumps, load
  File "C:\Users\hekan\anaconda3\envs\anytext\lib\site-packages\modelscope\fileio\io.py", line 8, in <module>
    from .format import JsonHandler, YamlHandler
  File "C:\Users\hekan\anaconda3\envs\anytext\lib\site-packages\modelscope\fileio\format\__init__.py", line 5, in <module>
    from .yaml import YamlHandler
  File "C:\Users\hekan\anaconda3\envs\anytext\lib\site-packages\modelscope\fileio\format\yaml.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
![20240105004134](https://github.com/tyxsspa/AnyText/assets/65994481/6442e5e3-3a7e-4cdf-a2a5-abd7bb66e0b9)

**Comment by tyxsspa** [comment]
yaml package not found. try install one:
```
pip install yaml
```

**Comment by heroki0817** [comment]
![20240106101723](https://github.com/tyxsspa/AnyText/assets/65994481/4ecb8312-d5d8-4d82-a10a-80d1a5b81345)
still had same error after installed yaml package, and I don't know why -_-
any suggestion?
> yxsspa
