### ISSUE TITLE
  RuntimeError: expected scalar type Half but found Float and unexpected keyword argument '_js

### ISSUE THREAD

**Issue by hl2dm** [tyxsspa/AnyText#41]
基本上我是缺什麼就裝什麼的狀態
單靠說明的步驟無法正確安裝 會缺一些依賴模組
再我補齊依賴模組並且裝上modelscope再
解決的utf8的問題後 碰到兩個問題
一個是在執行demo.py時:
WARNING:tensorflow:From C:\Users\DM\anaconda3\envs\modelscope\lib\site-packages\modelscope\models\nlp\csanmt\translation.py:793: calling while_loop_v2 (from tensorflow.python.ops.while_loop) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.while_loop(c, b, vars, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.while_loop(c, b, vars))
2024-01-07 21:40:11,869 - modelscope - INFO - loading model from C:\Users\DM\.cache\modelscope\hub\damo\cv_anytext_text_generation_editing\nlp_csanmt_translation_zh2en\tf_ckpts\ckpt-0
Traceback (most recent call last):
  File "demo.py", line 241, in <module>
    block.load(fn=None,
TypeError: event_trigger() got an unexpected keyword argument '_js'
一個是執行inference.py時:
  File "C:\Users\DM\anaconda3\envs\modelscope\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\TEXT\new\AnyText\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "C:\Users\DM\anaconda3\envs\modelscope\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\TEXT\new\AnyText\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "C:\Users\DM\anaconda3\envs\modelscope\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\TEXT\new\AnyText\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "D:\TEXT\new\AnyText\ldm\modules\diffusionmodules\util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\Users\DM\anaconda3\envs\modelscope\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\TEXT\new\AnyText\ldm\modules\diffusionmodules\util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "D:\TEXT\new\AnyText\ldm\modules\attention.py", line 272, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "C:\Users\DM\anaconda3\envs\modelscope\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\TEXT\new\AnyText\ldm\modules\attention.py", line 192, in forward
    out = einsum('b i j, b j d -> b i d', sim, v)
  File "C:\Users\DM\anaconda3\envs\modelscope\lib\site-packages\torch\functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: expected scalar type Half but found Float

重新安裝兩次都沒用
我懷疑是解決cp950時
我用with open('javascript/bboxHint.js', 'r', **encoding='UTF-8'**) as file: 的方式解決

**Comment by allankouidri** [comment]
Hi, I had the exact same error. I fixed it by installing xformers 

`
pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu118
`

I also updated torch, but that solved the issue in my case. 

Hope it helps.

**Comment by fuyunxiansen** [comment]
可以请教下是怎么解决的吗？
