### ISSUE TITLE
Traceback (most recent call last):   File "/ofs/test/AnyText/demo.py", line 241, in <module>     block.load(fn=None, TypeError: EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument '_js'

### ISSUE THREAD

**Issue by 1344663783** [tyxsspa/AnyText#46]
Traceback (most recent call last):
  File "/ofs/test/AnyText/demo.py", line 241, in <module>
    block.load(fn=None,
TypeError: EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument '_js'
有人遇到这个问题吗？

**Comment by tyxsspa** [comment]
Hi, check your gradio version please, 3.50.0 is recommended.
