### ISSUE TITLE
本地部署后运行出错 OSError: AnyTextPipeline: cannot open resource

### ISSUE THREAD

**Issue by QueenPuxxi** [tyxsspa/AnyText#50]
我的操作系统：Windows11

我的CUDA版本：11.1

我做了什么：
1.启动Anaconda虚拟环境anytext
2.在项目文件夹目录下输入`python inference.py`

终端命令行日志：
(anytext) D:\GitHubProject\AnyText>python inference.py
2024-01-11 13:38:36,229 - modelscope - INFO - PyTorch version 2.0.1 Found.
2024-01-11 13:38:36,287 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2024-01-11 13:38:36,287 - modelscope - INFO - Loading ast index from C:\Users\92923\.cache\modelscope\ast_indexer
2024-01-11 13:38:36,965 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 dece09f2ebbe99e0a53c20441372b40d and a total number of 946 components indexed
2024-01-11 13:38:45,385 - modelscope - INFO - Use user-specified model revision: v1.1.1
2024-01-11 13:39:03,504 - modelscope - WARNING - ('PIPELINES', 'my-anytext-task', 'anytext-pipeline') not found in ast index file
Traceback (most recent call last):
  File "D:\Anaconda3\envs\anytext\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\92923\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 336, in __init__
    pipe_model = AnyTextModel(model_dir=model, **kwargs)
  File "C:\Users\92923\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 46, in __init__
    self.init_model(**kwargs)
  File "C:\Users\92923\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 229, in init_model
    self.font = ImageFont.truetype(font_path, size=60)
  File "D:\Anaconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\Anaconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\Anaconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHubProject\AnyText\inference.py", line 3, in <module>
    pipe = pipeline('my-anytext-task', model='damo/cv_anytext_text_generation_editing', model_revision='v1.1.1')
  File "D:\Anaconda3\envs\anytext\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\Anaconda3\envs\anytext\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "D:\Anaconda3\envs\anytext\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: AnyTextPipeline: cannot open resource

**Comment by tyxsspa** [comment]
你好，字体文件需要自行准备，放到指定目录下

**Comment by QueenPuxxi** [comment]
谢谢！问题解决了！

**Comment by fatdennis** [comment]
如果字體已放了在指定目錄下，但仍出現以下，可怎樣處理？

Traceback (most recent call last):
  File "C:\Users\Dennis\.conda\envs\anytext\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\Dennis\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 336, in __init__
    pipe_model = AnyTextModel(model_dir=model, **kwargs)
  File "C:\Users\Dennis\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 46, in __init__
    self.init_model(**kwargs)
  File "C:\Users\Dennis\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 229, in init_model
    self.font = ImageFont.truetype(font_path, size=60)
  File "C:\Users\Dennis\.conda\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "C:\Users\Dennis\.conda\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\Dennis\.conda\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: cannot open resource

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\AnyText\inference.py", line 3, in <module>
    pipe = pipeline('my-anytext-task', model='damo/cv_anytext_text_generation_editing', model_revision='v1.1.1')
  File "C:\Users\Dennis\.conda\envs\anytext\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "C:\Users\Dennis\.conda\envs\anytext\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "C:\Users\Dennis\.conda\envs\anytext\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: AnyTextPipeline: cannot open resource

**Comment by maliho0803** [comment]
必须Arial Unicode MS 这个字体？

**Comment by luoan7248** [comment]
> Arial Unicode MS
你好，请问有字体的下载连接吗，我下了几个都不行

**Comment by NaughtyZZ** [comment]
同问，下了好几个字体都不行
