### ISSUE TITLE
what is the matter about : modelscope - WARNING - ('PIPELINES', 'my-anytext-task', 'anytext-pipeline') not found in ast index file

### ISSUE THREAD

**Issue by 2017867924** [tyxsspa/AnyText#63]
win10 rtx3080ti runtimes show the exception，pls help.
==================cmd :==================
(anytext) D:\ws_ai_comfyui\AnyText\AnyText>python inference.py
2024-01-26 16:25:15,655 - modelscope - INFO - PyTorch version 2.0.1 Found.
2024-01-26 16:25:15,656 - modelscope - INFO - TensorFlow version 2.13.0 Found.
2024-01-26 16:25:15,656 - modelscope - INFO - Loading ast index from C:\Users\Administrator\.cache\modelscope\ast_indexer
2024-01-26 16:25:15,700 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 9499acdccf8777a2ba84c3c0617307a1 and a total number of 946 components indexed
2024-01-26 16:25:19,394 - modelscope - INFO - Use user-specified model revision: v1.1.1
2024-01-26 16:25:22,610 - modelscope - WARNING - ('PIPELINES', 'my-anytext-task', 'anytext-pipeline') not found in ast index file
Traceback (most recent call last):
  File "D:\dev_tool\anaconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 996, in truetype
    return freetype(font)
  File "D:\dev_tool\anaconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\dev_tool\anaconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: unknown file format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev_tool\anaconda3\envs\anytext\lib\site-packages\modelscope\utils\registry.py", line 212, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\Administrator\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 336, in __init__
    pipe_model = AnyTextModel(model_dir=model, **kwargs)
  File "C:\Users\Administrator\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 46, in __init__
    self.init_model(**kwargs)
  File "C:\Users\Administrator\.cache\modelscope\modelscope_modules\cv_anytext_text_generation_editing\ms_wrapper.py", line 229, in init_model
    self.font = ImageFont.truetype(font_path, size=60)
  File "D:\dev_tool\anaconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 1030, in truetype
    return freetype(os.path.join(walkroot, walkfilename))
  File "D:\dev_tool\anaconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 993, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\dev_tool\anaconda3\envs\anytext\lib\site-packages\PIL\ImageFont.py", line 248, in __init__
    self.font = core.getfont(
OSError: unknown file format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ws_ai_comfyui\AnyText\AnyText\inference.py", line 3, in <module>
    pipe = pipeline('my-anytext-task', model='damo/cv_anytext_text_generation_editing', model_revision='v1.1.1')
  File "D:\dev_tool\anaconda3\envs\anytext\lib\site-packages\modelscope\pipelines\builder.py", line 170, in pipeline
    return build_pipeline(cfg, task_name=task)
  File "D:\dev_tool\anaconda3\envs\anytext\lib\site-packages\modelscope\pipelines\builder.py", line 65, in build_pipeline
    return build_from_cfg(
  File "D:\dev_tool\anaconda3\envs\anytext\lib\site-packages\modelscope\utils\registry.py", line 215, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: AnyTextPipeline: unknown file format

**Comment by DougPP** [comment]
I get the same errors (Warning - Pipelines, registry.py anytextpipeline unknown)

**Comment by ibou810** [comment]
hello , did you fix the error ?
