### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by lucasjinreal** [tyxsspa/AnyText#8]
Traceback (most recent call last):
  File "demo.py", line 33, in <module>
    class ScriptLoader:
  File "demo.py", line 45, in ScriptLoader
    def get_scripts(path: str, file_type: str) -> list[tuple[str, str]]:
TypeError: 'type' object is not subscriptable

I got this error evnetually when installed torch tensorflow and whole universe this project need....

**Comment by lucasjinreal** [comment]
Do we really need using python3.9 synatax when you can easily make it compatible with python3.8 and python3.7 ?
